import type { Metadata } from "next";
import { Inter, Fira_Code, Bebas_Neue } from "next/font/google";
import "./globals.css";
import { Providers } from './providers';
import ThemeToggleButton from './components/theme-toggle/ThemeToggleButton';

import Footer from './components/layout/Footer';

const bebasNeue = Bebas_Neue({
  subsets: ['latin'],
  weight: "400",
  variable: '--font-bebas-neue',
});

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const firaCode = Fira_Code({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="dark">
      <body className={`${bebasNeue.className} ${inter.variable} ${firaCode.variable} antialiased`}>
        <Providers>
          <main className="container py-8 relative">
            <div className="absolute top-4 right-4 z-10">
              <ThemeToggleButton />
            </div>
            {children}
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
