import type { Metadata } from "next";
import { Inter, Fira_Code } from "next/font/google";
import "./globals.css";
import { Providers } from './providers'; // Import Providers

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const firaCode = Fira_Code({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="min-h-screen bg-white text-gray-900 dark:bg-zinc-900 dark:text-gray-100 font-sans transition-colors duration-300">
      <body className={`${inter.variable} ${firaCode.variable} antialiased min-h-screen bg-white dark:bg-zinc-900 text-gray-900 dark:text-gray-100 font-sans transition-colors duration-300`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
